name: express-app-test
services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./infra/ec2/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - network-a
    restart: always
  server:
    image: ksot1233/express
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20.12.1
      tags:
        - ksot1233/express:latest
      pull: true

    container_name: express-app
    restart: always
    env_file:
      - .env.production
    environment:
      - SERVER_PORT=3000
    expose:
      - "3000"
    networks:
      - network-a
    volumes:
      - volume-a:/app/logs:rw

networks:
  network-a:

volumes:
  volume-a:
