name: express-app-test
services:
  server:
    image: ksot1233/express
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20.12.1
      tags:
        - ksot1233/express:latest
      pull: true

    container_name: express-app
    env_file:
      - .env
    environment:
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - network-a
    volumes:
      - volume-a:/app/logs:rw
  db:
    image: postgres
    env_file:
      - .env.db
    ports:
      - "5434:5432"
    networks:
      - network-a

networks:
  network-a:

volumes:
  volume-a:
