### 회원가입 요청
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "you12@example.com",
  "password": "password1234",
  "nickname": "도준",
  "image": "https://example.com/profile.jpg"
}

### 로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "you1234@example.com",
  "password": "password1234"
}


### 알림 목록 조회 (전체 또는 읽지 않은 것만 조회)
GET http://localhost:3000/users/notification?
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NzMwMDg4MSwiZXhwIjoxNzQ3MzA0NDgxfQ.w3IMFpOljXszobk1DdsIEEoqYpBW-5-jswcXWUY6jGw