### 회원가입 요청
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "you12@example.com",
  "password": "password1234",
  "nickname": "도준",
  "image": "https://example.com/profile.jpg"
}

### 로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "you12@example.com",
  "password": "password1234"
}