name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          port: 22
          script: |
            set -e
            cd ~/1-sprint-mission/5-sprint-mission # EC2 인스턴스 내 프로젝트 경로로 진입
            git reset --hard
            git clean -fd
            git pull origin main # 코드 최신화
            npm install
            npm run build
            npm run prisma:deploy
            pm2 reload mission
            echo "Deployment successful!"
