name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          port: 22
          script: |
            cd ~/1-sprint-mission/5-sprint-mission # EC2 인스턴스 내 프로젝트 경로로 진입
            git reset --hard HEAD
            git pull origin main # 코드 최신화
            cd ~/1-sprint-mission
            chmod +x ./5-sprint-mission/infra/ec2/start.sh
            ./5-sprint-mission/infra/ec2/start.sh
            echo "Deployment successful!"
